language: node_js

node_js:
  - "stable"

dist: trusty

sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - yarn install
  - yarn generate
  - yarn deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
