language: node_js

node_js:
  - "stable"

dist: trusty

sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - yarn install
  - yarn generate
  - yarn deploy
